version: '3'

services:

    web:
      image: nginx:1.17.10
      container_name: nginx
      hostname: nginx
      #command: chown -R nginx:nginx /var/lib/nginx
      volumes:
        - ./html:/usr/share/nginx/html
        - ./templates/nginx.conf:/etc/nginx/nginx.conf
        - ./servers:/etc/nginx/modules-enabled/
        - ./logs:/usr/share/nginx/logs
      ports:
        - "80:80"
        - "8001:8001"
        - "8002:8002"
      networks:
        - node-teste
      depends_on:
        - laravel

    laravel:
      image: devbode/laravel
      hostname: laravel
      container_name: laravel
      ports:
        - "8000:80"
      networks:
        - node-teste

networks:
  node-teste:
    driver: bridge