version: '3'

services:

    web:
      image: nginx
      container_name: nginx
      hostname: nginx
      volumes:
        - "./html:/var/www/html/"
        - "./servers:/etc/nginx/conf.d/"
      ports:
        - "80:80"
        - "70:70"
        - "8080:8080"
        - "8888:8888"